### ISSUE TITLE
Cruz and Kasich have dropped out. Add Gary Johnson.

### ISSUE THREAD

**Issue by ScottElliotTaxFoundation** [TaxFoundation/tax-plans#48]
For Gary Johnson, put "No specific proposal." under each category.

**Comment by tvanantwerp** [comment]
@cpastre1 Do we have a Gary Johnson photo we use like we do for everyone else?

**Comment by cpastre1** [comment]
Here you go: https://www.dropbox.com/s/ekwgfly5mm5kfdp/Gary.jpg?dl=0

There's a circle-cropped version here if you need it, too: https://www.dropbox.com/s/zax9eeh17aid10h/Gary.png?dl=0
