### ISSUE TITLE
Updates to Jindal

### ISSUE THREAD

**Issue by ScottElliotTaxFoundation** [TaxFoundation/tax-plans#9]
Rates on Ordinary Income
"Establishes three tax brackets, with rates of 2%, 10%, and 25%. The top rate applies to taxable income over $90,000 for single filers and $180,000 for joint filers. Eliminates the standard deduction and the personal exemption."

Itemized Deductions
"Eliminates all itemized deductions, except for the charitable deduction and the mortgage interest deduction. Caps the mortgage interest deduction at $500,000 of interest payments. Eliminates the Pease limitation on itemized deductions."

Credits
"Replaces the personal exemption with a nonrefundable credit for dependents. Transfers the earned income tax credit to the payroll tax."

Alternative Minimum Tax
"Eliminates the alternative minimum tax."

Rates on Capital Gains and Dividends Income
"Taxes capital gains and dividends as ordinary income. Eliminates the net investment income surtax."

Top Rates on Corporate Income
"Eliminates the corporate income tax."

International Income
Shifts to a territorial tax system and enacts a deemed repatriation of foreign income at a 8% rate.

Estate Taxes
"Eliminates the estate tax."

Other
"Creates tax-free savings accounts for up to $30,000 of savings a year."
[We can eliminate the text that was previously in 'Other']

**Comment by tvanantwerp** [comment]
Nothing on Capital Investment, Pass-throughs, or Payroll Taxes?

**Comment by ScottElliotTaxFoundation** [comment]
Yes, that's correct
